### ISSUE TITLE
rdkit-pypi dependency

### ISSUE THREAD

**Issue by kjelljorner** [dewberryants/asciiMol#10]
asciiMol is a really cool project, but the dependency on rdkit-pypi is quite limiting imho. There are other and arguably better ways to install RDKit, including the conda package manager. In the spirit of a terminal program, I think it would make more sense to have xyz generation from smiles as a separate first step, for example

```shell
gen_xyz_from_smiles "CCCC" > butane.xyz
asciimol butane.xyz
```

Anyway, if you want to keep it, I think the best thing is to make rdkit-pypi an optional dependency. It is anyway imported only within the function `read_smiles`.

**Comment by dewberryants** [comment]
I agree with this... I've been thinking of adding several optional dependencies that can resolve formats other than .xyz and then simply delegate in order of their availability. I'll link my ASE PR for now, and hopefully I'll get around to this soon.

**Comment by kjelljorner** [comment]
I made a fork with a setup.py, mostly for installing for myself. It could be installed with `pip install asciimol[rdkit]` to install the optional dependency: https://github.com/kjelljorner/asciiMol/blob/05a1d8ca04e549ee6bbb9dd318a885960fcb0df8/setup.py#L20. Besides ASE, you can also take a look at [cclib](https://cclib.github.io) and [chemfiles](https://chemfiles.org)
