### ISSUE TITLE
Positive Feedback

### ISSUE THREAD

**Issue by whitead** [dewberryants/asciiMol#2]
Really cool project! Shared [it with some friends on Twitter](https://twitter.com/andrewwhite01/status/1486075237129199622) and thought you'd like to see the very positive response.

**Comment by dewberryants** [comment]
Awesome, thank you! I wrote this because I regularily mixed up molecules on our HPC cluster. :) I suppose I should really revisit this sometime and give it some more love if you guys find it useful. Cheers!
